[versions]
agp = "9.0.1"
annotation = "1.9.1"
viewpager = "1.1.0"
junit4 = "4.13.2"
androidxJunit = "1.3.0"
espresso = "3.7.0"
androidxTestCore = "1.7.0"
robolectric = "4.16.1"
ktlintCli = "1.3.1"
detektCli = "1.23.8"
roborazzi = "1.52.0"
composeBom = "2025.10.00"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlintCli" }
detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detektCli" }
roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-junit-rule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
