[versions]
agp = "9.0.1"
annotation = "1.9.1"
viewpager = "1.0.0"
junit4 = "4.13.2"
androidxJunit = "1.3.0"
espresso = "3.7.0"
androidxTestCore = "1.7.0"
robolectric = "4.13"
composeBom = "2025.10.00"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
